# Generated by Django 5.0.2 on 2024-07-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company_profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_profiles',
            field=models.ManyToManyField(related_name='user_profiles', to='companies.companyprofile'),
        ),
    ]
