# Generated by Django 5.0.2 on 2024-08-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('PROFILE_UPDATE', 'Profile Update'), ('PASSWORD_CHANGE', 'Password Change'), ('EMAIL_CHANGE', 'Email Change')], default='EMAIL_CHANGE', max_length=50),
            preserve_default=False,
        ),
    ]
