# Generated by Django 5.0.2 on 2024-09-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useractivity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('ACCOUNT_CREATION', 'Account Creation'), ('ACCESS_PERMISSION_GRANTED', 'Access Permission Granted'), ('ACCESS_PERMISSION_REVOKED', 'Access Permission Revoked'), ('COMMENT_UPDATE', 'Comment Update'), ('DOCUMENT_DOWNLOAD', 'Document Download'), ('DOCUMENT_UPDATE', 'Document Update'), ('DOCUMENT_UPLOAD', 'Document Upload'), ('EMAIL_CHANGE', 'Email Change'), ('EMAIL_PREFERENCE_UPDATE', 'Email Preferences Updated'), ('EXPORT_CREATION', 'Export Creation'), ('EXPORT_UPDATE', 'Export Update'), ('FEEDBACK_SUBMITTED', 'Feedback Submitted'), ('FOLDER_CREATION', 'Folder Creation'), ('FOLDER_UPDATE', 'Folder Update'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('NOTIFICATION_SETTING_UPDATE', 'Notification Settings Updated'), ('PARTNERSHIP_ACCEPT', 'Partnership Invite Accepted'), ('PARTNERSHIP_INVITE', 'Partnership Invite Sent'), ('PASSWORD_CHANGE', 'Password Change'), ('PRIVACY_SETTING_UPDATE', 'Privacy Settings Updated'), ('PRODUCT_CREATION', 'Product Creation'), ('PRODUCT_UPDATE', 'Product Update'), ('PROFILE_UPDATE', 'Profile Update'), ('SUPPORT_TICKET_CREATED', 'Support Ticket Created'), ('SUPPORT_TICKET_RESOLVED', 'Support Ticket Resolved'), ('TOKEN_USED', 'Company Token Used')], max_length=50),
        ),
    ]
