# Generated by Django 5.0.2 on 2024-02-23 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
        ('products', '0002_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='folder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='products.product'),
        ),
    ]
