# Generated by Django 5.0.2 on 2024-03-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_folder_created_at_folder_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
