# Generated by Django 5.0.2 on 2024-04-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0004_folder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='bin_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_bin',
            field=models.BooleanField(default=False),
        ),
    ]
