# Generated by Django 5.0.2 on 2024-04-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0005_folder_bin_expires_at_folder_is_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='original_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='folder.folder'),
        ),
    ]
