# Generated by Django 5.0.2 on 2024-02-20 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exporter_partnerships', to=settings.AUTH_USER_MODEL)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importer_partnerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exporter', 'importer')},
            },
        ),
    ]
