# Generated by Django 5.0.2 on 2024-07-24 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_as_partner1', to=settings.AUTH_USER_MODEL)),
                ('partner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_as_partner2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('partner1', 'partner2')},
            },
        ),
    ]
