# Generated by Django 5.0.2 on 2024-02-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
    ]
