# Generated by Django 5.0.2 on 2024-08-17 06:49

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file_alter_documentversion_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to=documents.models.document_upload_to),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(max_length=500, upload_to=documents.models.document_version_upload_to),
        ),
    ]
