# Generated by Django 5.0.2 on 2024-03-14 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_deleted_at_documentversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to='document_versions/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
