# Generated by Django 5.0.2 on 2024-09-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_companyprofile_profile_image'),
        ('documents', '0003_alter_document_file_alter_documentversion_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_versions', to='companies.companyprofile'),
        ),
    ]
