# Generated by Django 5.0.2 on 2024-03-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentversion_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='original_filename',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
