# Generated by Django 5.0.2 on 2024-03-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
