# Generated by Django 5.0.2 on 2024-04-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_documentversion_updated_at_and_more'),
        ('folder', '0006_folder_original_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='folder.folder'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='original_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='folder.folder'),
        ),
    ]
