# Generated by Django 5.0.2 on 2024-04-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_document_original_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='bin_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
