# Generated by Django 5.0.2 on 2024-05-11 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_document_type'),
        ('exports', '0001_initial'),
        ('partners', '0001_initial'),
        ('products', '0002_product_product_code_alter_product_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportdocument',
            name='export_partner',
        ),
        migrations.AddField(
            model_name='export',
            name='partnership',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='partners.partnership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportdocument',
            name='export',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='exports.export'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='export',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_documents', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='exportproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_exports', to='products.product'),
        ),
        migrations.DeleteModel(
            name='ExportPartner',
        ),
    ]
