# Generated by Django 5.0.2 on 2024-05-11 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_document_type'),
        ('exports', '0002_remove_exportdocument_export_partner_and_more'),
        ('folder', '0007_alter_folder_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='export',
            old_name='partnership',
            new_name='partner',
        ),
        migrations.AddField(
            model_name='exportdocument',
            name='folder',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.CASCADE, related_name='folder_exports', to='folder.folder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='export',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_exports', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='exportdocument',
            name='export',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_documents', to='exports.export'),
        ),
    ]
