# Generated by Django 5.0.2 on 2024-05-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0003_rename_partnership_export_partner_and_more'),
        ('folder', '0007_alter_folder_product'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='partner',
        ),
        migrations.AddField(
            model_name='export',
            name='folder',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='export_folders', to='folder.folder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='export',
            name='partners',
            field=models.ManyToManyField(related_name='exports', to='partners.partnership'),
        ),
    ]
