# Generated by Django 5.0.2 on 2024-05-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0004_remove_export_partner_export_folder_export_partners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='export',
            old_name='partners',
            new_name='partner',
        ),
    ]
