# Generated by Django 5.0.2 on 2024-05-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0005_rename_partners_export_partner'),
        ('folder', '0007_alter_folder_product'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='folder',
        ),
        migrations.CreateModel(
            name='PartnerExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exports.export')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder.folder')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partnership')),
            ],
        ),
    ]
