# Generated by Django 5.0.2 on 2024-05-12 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0006_remove_export_folder_partnerexport'),
        ('folder', '0007_alter_folder_product'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerexport',
            name='export',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_exports', to='exports.export'),
        ),
        migrations.AlterField(
            model_name='partnerexport',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_export_folders', to='folder.folder'),
        ),
        migrations.AlterField(
            model_name='partnerexport',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_exports', to='partners.partnership'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerexport',
            unique_together={('partner', 'export')},
        ),
    ]
