# Generated by Django 5.0.2 on 2024-05-19 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0007_alter_partnerexport_export_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='export_date',
        ),
        migrations.RemoveField(
            model_name='export',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='exportdocument',
            name='export',
        ),
        migrations.RemoveField(
            model_name='exportproduct',
            name='export',
        ),
        migrations.AddField(
            model_name='export',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='export',
            name='reference_number',
            field=models.CharField(default='EXP20230515001', max_length=100, unique=True, verbose_name='Reference Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportdocument',
            name='partner_export',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='export_documents', to='exports.partnerexport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportproduct',
            name='partner_export',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='export_products', to='exports.partnerexport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerexport',
            name='export_date',
            field=models.DateField(default='2023-5-15', verbose_name='Export Date'),
            preserve_default=False,
        ),
    ]
