# Generated by Django 5.0.2 on 2024-05-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0008_remove_export_export_date_remove_export_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerexport',
            name='export_date',
            field=models.DateField(blank=True, null=True, verbose_name='Export Date'),
        ),
    ]
