# Generated by Django 5.0.2 on 2024-05-19 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0009_alter_partnerexport_export_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='export_date',
            field=models.DateField(blank=True, null=True, verbose_name='Export Date'),
        ),
        migrations.AlterField(
            model_name='export',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Reference Number'),
        ),
        migrations.CreateModel(
            name='StagedPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'partner')},
            },
        ),
    ]
