# Generated by Django 5.0.2 on 2024-06-17 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0010_export_export_date_alter_export_reference_number_and_more'),
        ('folder', '0007_alter_folder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='export_date',
            field=models.DateField(verbose_name='Export Date'),
        ),
        migrations.AlterField(
            model_name='exportdocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_exports', to='folder.folder'),
        ),
        migrations.AlterField(
            model_name='partnerexport',
            name='export_date',
            field=models.DateField(verbose_name='Export Date'),
        ),
        migrations.AlterField(
            model_name='partnerexport',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_export_folders', to='folder.folder'),
        ),
        migrations.DeleteModel(
            name='StagedPartner',
        ),
    ]
