# Generated by Django 5.0.2 on 2024-06-17 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_document_type'),
        ('exports', '0011_alter_export_export_date_alter_exportdocument_folder_and_more'),
        ('folder', '0007_alter_folder_product'),
        ('partners', '0001_initial'),
        ('products', '0004_remove_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportproduct',
            name='partner_export',
        ),
        migrations.RemoveField(
            model_name='exportproduct',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='partnerexport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='partnerexport',
            name='export',
        ),
        migrations.RemoveField(
            model_name='partnerexport',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='partnerexport',
            name='partner',
        ),
        migrations.AddField(
            model_name='export',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='exports', to='documents.document'),
        ),
        migrations.AddField(
            model_name='export',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='folder.folder'),
        ),
        migrations.AddField(
            model_name='export',
            name='partner',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='partners.partnership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='export',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='exports', to='products.product'),
        ),
        migrations.DeleteModel(
            name='ExportDocument',
        ),
        migrations.DeleteModel(
            name='ExportProduct',
        ),
        migrations.DeleteModel(
            name='PartnerExport',
        ),
    ]
