# Generated by Django 5.0.2 on 2024-06-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0012_remove_exportproduct_partner_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
