# Generated by Django 5.0.2 on 2024-07-24 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, choices=[('trading', 'Trading'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('food service', 'Food Service'), ('manufacturer', 'Manufacturer'), ('logistics', 'Logistics'), ('financial services', 'Financial services'), ('insurance', 'Insurance'), ('government agency', 'Government Agency'), ('other', 'Other')], max_length=20, null=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partners_contract_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='folder.folder')),
            ],
        ),
    ]
