# Generated by Django 5.0.2 on 2024-08-04 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, choices=[('trading', 'Trading'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('food service', 'Food Service'), ('manufacturer', 'Manufacturer'), ('logistics', 'Logistics'), ('financial services', 'Financial services'), ('insurance', 'Insurance'), ('government agency', 'Government Agency'), ('other', 'Other')], max_length=20, null=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invite_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('token_uses', models.IntegerField(default=0)),
                ('max_token_uses', models.IntegerField(default=2)),
            ],
        ),
    ]
