# Generated by Django 5.0.2 on 2024-08-18 05:20

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=companies.models.company_profile_image_upload_to),
        ),
    ]
