# Generated by Django 5.0.2 on 2024-07-24 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_type', models.CharField(choices=[('read_only', 'Read Only'), ('full', 'Full')], default='full', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Access Permissions',
            },
        ),
    ]
