# Generated by Django 5.0.2 on 2024-08-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('companies', '0002_initial'),
        ('documents', '0001_initial'),
        ('folder', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspermission',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folder.folder'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='partner1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to='companies.companyprofile'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='partner2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_permissions', to='companies.companyprofile'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='accesspermission',
            unique_together={('partner1', 'partner2', 'product', 'folder', 'document')},
        ),
    ]
