# Generated by Django 5.0.2 on 2024-04-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspermission',
            name='access_type',
            field=models.CharField(choices=[('read_only', 'Read Only'), ('full', 'Full')], default='Full', max_length=50),
            preserve_default=False,
        ),
    ]
