# Generated by Django 5.0.2 on 2024-09-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspermission',
            name='is_direct',
            field=models.BooleanField(default=True),
        ),
    ]
