# Generated by Django 5.0.2 on 2024-04-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_accesspermission_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspermission',
            name='access_type',
            field=models.CharField(choices=[('read_only', 'Read Only'), ('full', 'Full')], default='full', max_length=50),
        ),
    ]
