# Generated by Django 5.0.2 on 2024-08-04 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
