# Generated by Django 5.0.2 on 2024-03-05 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('meat_products', 'Meat Products'), ('poultry_products', 'Poultry Products'), ('egg_products', 'Egg Products'), ('seafood', 'Seafood'), ('dairy_products', 'Dairy Products'), ('fruits_vegetables', 'Fruits and Vegetables'), ('grains_cereals', 'Grains and Cereals'), ('processed_foods', 'Processed Foods')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
