# Generated by Django 5.0.2 on 2024-02-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('meat_products', 'Meat Products'), ('poultry_products', 'Poultry Products'), ('egg_products', 'Egg Products'), ('seafood', 'Seafood'), ('dairy_products', 'Dairy Products'), ('fruits_vegetables', 'Fruits and Vegetables'), ('grains_cereals', 'Grains and Cereals'), ('processed_foods', 'Processed Foods')], default='Processed Foods', max_length=20),
            preserve_default=False,
        ),
    ]
